version: "3.9"
services:
  client:
    build:
      context: ./conventus-client
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - conventus-net

  server:
    build:
      context: .
      dockerfile: Conventus.API/Dockerfile
    container_name: conventus-server
    ports:
      - "5082:5082"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - sqlserver
    networks:
      - conventus-net

  sqlserver:
    build:
        context: .
        dockerfile: Dockerfile.sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "xkukht01@password"
      ACCEPT_EULA: "Y"
    networks:
      - conventus-net
    volumes:
      - sql_data:/var/opt/sqlserver
    command: /opt/mssql/bin/sqlservr

  sqlserver-init:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver_init
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver-init
    depends_on:
      - sqlserver
    command: /bin/bash -c "sleep 120 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'xkukht01@password' -i /docker-entrypoint-initdb.d/init.sql"
    networks:
      - conventus-net
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  sql_data:

networks:
  conventus-net:
    driver: bridge
